engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: .eslintrc1
  fixme:
    enabled: true
exclude_paths:
- spec/
