language: node_js
before_script:
  - npm install -g codeclimate-test-reporter
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - coveralls < coverage/lcov.info
